### ISSUE TITLE
Make the NAVBAR mobile responsive

### ISSUE THREAD

**Issue by Akash-Kumar-Sen** [Akash-Kumar-Sen/EdexCare#2]
- The existing navigation bar is not mobile responsive. Make it mobile responsive.

**Comment by rajmunkhan** [comment]
@Akash-Kumar-Sen I would like to work on this issue, plz assign it to me

**Comment by Aditya3403** [comment]
Can I help you with that

**Comment by Aditya3403** [comment]
Can I help you with that as I know how to make website mobile responsive.

**Comment by Aditya3403** [comment]
Sir please assign me this as I know how to make it mobile responsive.

**Comment by nitishapiplani** [comment]
i would like to work on same

**Comment by Akash-Kumar-Sen** [comment]
@Aditya3403  I am assigning this issue to you.

**Comment by Aditya3403** [comment]
Sir I would not be able to complete this on time as there some issue in installing python in my laptop.
Sir please assign it to someone else.
